# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  #config.vm.define :box, primary: true do |box|
  #    box.vm.box = 'centos/8'
  #    box.vm.network :public_network, ip: '192.168.1.160'
  #end

  config.vm.box = "centos/8"
  config.vm.hostname = "node-cn"
  config.vm.network :private_network, :ip => "192.168.124.10"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  # config.vm.synced_folder "../data", "/home/vagrant/data", type: "nfs"
  # config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

  config.vm.provider :libvirt do |libvirt|
    # libvirt.host = "192.168.1.10"
    # libvirt.connect_via_ssh = true
    # libvirt.username = virtual
    # libvirt.password = virtual
    # libvirt.id_ssh_key_file = "id_rsa"
    libvirt.uri = "qemu+ssh://virtual@192.168.1.10/system"
    #libvirt.driver = 'kvm'

    libvirt.memory = 2048
    libvirt.cpus = 2
    #libvirt.machine_virtual_size = '30G'
    # libvirt.storage :file, :size => '40G'
  end

  config.vm.provision "shell", inline: <<-SHELL
    /vagrant/install.sh
  SHELL
end
