# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provider "parallels" do |p, o|
    p.memory = "2048"
  end
  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
    end
  end

  # Increase memory for LibVirt and add devices for gueat agent
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
    libvirt.driver = 'kvm'
  end

  config.vm.define "minikube" do |node|
    node.vm.box = "centos/8"
    node.vm.hostname = "minikube.example.com"
    node.vm.provision "shell", path: "bootstrap.sh"
  end

end

